# Generated by Django 3.2.7 on 2021-09-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('master', models.CharField(max_length=255, verbose_name='Хозяин')),
                ('age', models.CharField(max_length=255, verbose_name='Возраст')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
            ],
        ),
    ]
