# Generated by Django 3.2.7 on 2021-09-15 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('quantity', models.CharField(max_length=255, verbose_name='Количество')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
            ],
        ),
    ]
