# Generated by Django 3.2.7 on 2021-09-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=255, verbose_name='Марка')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('year', models.CharField(max_length=255, verbose_name='Количество')),
                ('price', models.FloatField(verbose_name='Цена')),
                ('comment', models.CharField(max_length=255, verbose_name='Комментарий')),
            ],
        ),
    ]
